HISTORICAL_EVENTS = [
    {
        "id": 1,
        "title": "Montgomery Bus Boycott",
        "year": 1955,
        "description": "A political and social protest campaign against the policy of racial segregation on the public transit system of Montgomery, Alabama. The campaign lasted from December 5, 1955 — the Monday after Rosa Parks, an African American woman, was arrested for refusing to surrender her seat to a white person — to December 20, 1956.",
        "significance": "Sparked the modern civil rights movement and led to the desegregation of public buses. The boycott also propelled Martin Luther King Jr. to national prominence as a civil rights leader.",
        "location": "Montgomery, Alabama",
        "key_figures": ["Rosa Parks", "Martin Luther King Jr.", "E.D. Nixon", "Jo Ann Robinson"],
    },
    {
        "id": 2,
        "title": "March on Washington for Jobs and Freedom",
        "year": 1963,
        "description": "A political rally for civil rights and economic equality that took place in Washington, D.C. on August 28, 1963. More than 250,000 people attended, making it the largest political rally for civil rights in U.S. history at that time.",
        "significance": "Helped pass the Civil Rights Act of 1964 and Voting Rights Act of 1965. Martin Luther King Jr.'s 'I Have a Dream' speech became one of the most famous speeches in American history.",
        "location": "Washington, D.C.",
        "key_figures": ["Martin Luther King Jr.", "A. Philip Randolph", "Bayard Rustin", "John Lewis"],
    },
    {
        "id": 3,
        "title": "Brown v. Board of Education Decision",
        "year": 1954,
        "description": "The Supreme Court declared that racial segregation in public schools was unconstitutional, overturning the 'separate but equal' doctrine established in Plessy v. Ferguson (1896).",
        "significance": "Landmark decision that led to the desegregation of public schools and became a catalyst for the civil rights movement. The ruling declared that segregation inherently created inequality.",
        "location": "United States Supreme Court",
        "key_figures": ["Thurgood Marshall", "Chief Justice Earl Warren", "Oliver Brown", "NAACP Legal Defense Team"],
    },
    {
        "id": 4,
        "title": "Tuskegee Syphilis Study Exposure",
        "year": 1972,
        "description": "A whistleblower revealed that the U.S. Public Health Service had been conducting an unethical study on 399 Black men with syphilis in Tuskegee, Alabama, without their informed consent, denying them treatment for decades.",
        "significance": "Led to major reforms in medical ethics, informed consent requirements, and increased distrust of medical institutions in Black communities. Resulted in the establishment of IRBs (Institutional Review Boards).",
        "location": "Tuskegee, Alabama",
        "key_figures": ["Peter Buxtun (whistleblower)", "Fred Gray (attorney)", "Study participants"],
    },
    {
        "id": 5,
        "title": "Harlem Renaissance",
        "year": 1920,
        "description": "A cultural, social, and artistic explosion centered in Harlem, New York, spanning the 1920s to mid-1930s. It was considered a rebirth of African American arts and became known as the 'New Negro Movement'.",
        "significance": "Established a foundation for modern Black culture and identity. Produced some of the greatest works of literature, music, and art in American history. Created a new sense of Black pride and consciousness.",
        "location": "Harlem, New York City",
        "key_figures": ["Langston Hughes", "Zora Neale Hurston", "Duke Ellington", "Louis Armstrong", "Aaron Douglas"],
    },
    {
        "id": 6,
        "title": "Freedom Summer",
        "year": 1964,
        "description": "A volunteer campaign in Mississippi to register Black voters and establish 'Freedom Schools' to teach civics, politics, and Black history. Over 1,000 volunteers, mostly white college students, participated.",
        "significance": "Brought national attention to voter suppression in the South. The murders of three civil rights workers (James Chaney, Andrew Goodman, and Michael Schwerner) shocked the nation and helped pass the Voting Rights Act of 1965.",
        "location": "Mississippi",
        "key_figures": ["Bob Moses", "Fannie Lou Hamer", "James Chaney", "Andrew Goodman", "Michael Schwerner"],
    },
    {
        "id": 7,
        "title": "Emancipation Proclamation",
        "year": 1863,
        "description": "President Abraham Lincoln issued the Emancipation Proclamation, declaring that all enslaved people in Confederate states were to be set free. The proclamation took effect on January 1, 1863.",
        "significance": "Transformed the Civil War into a fight for human freedom and allowed Black men to serve in the Union Army. Though it didn't immediately free all enslaved people, it laid the groundwork for the 13th Amendment.",
        "location": "United States",
        "key_figures": ["Abraham Lincoln", "Frederick Douglass", "Enslaved people seeking freedom"],
    },
    {
        "id": 8,
        "title": "Civil Rights Act of 1964",
        "year": 1964,
        "description": "Landmark legislation that outlawed discrimination based on race, color, religion, sex, or national origin. It ended unequal application of voter registration requirements and racial segregation in schools, workplaces, and public accommodations.",
        "significance": "The most comprehensive civil rights legislation since Reconstruction. It transformed American society by legally ending segregation and discrimination in public places and employment.",
        "location": "United States Congress",
        "key_figures": ["Lyndon B. Johnson", "Martin Luther King Jr.", "Hubert Humphrey", "Everett Dirksen"],
    },
]
