HISTORICAL_FIGURES = [
    {
        "id": 1,
        "name": "Dr. Martin Luther King Jr.",
        "birth_year": 1929,
        "death_year": 1968,
        "profession": "Civil Rights Leader & Nobel Peace Prize Winner",
        "achievements": [
            "Led the Montgomery Bus Boycott (1955-1956)",
            "Delivered iconic 'I Have a Dream' speech at March on Washington (1963)",
            "Won Nobel Peace Prize in 1964 at age 35",
            "Led Selma to Montgomery marches for voting rights (1965)",
            "Founded Southern Christian Leadership Conference (SCLC)",
        ],
        "biography": "Dr. Martin Luther King Jr. was an American Baptist minister and activist who became the most visible spokesperson and leader in the civil rights movement from 1955 until his assassination in 1968. Born in Atlanta, Georgia, King is best known for advancing civil rights through nonviolence and civil disobedience, inspired by his Christian beliefs and the nonviolent activism of Mahatma Gandhi.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/0/05/Martin_Luther_King_Jr._delivering_I_Have_a_Dream_at_the_1963_Washington_D.C._Civil_Rights_March.jpg",
        "category": "Civil Rights Leaders",
    },
    {
        "id": 2,
        "name": "Maya Angelou",
        "birth_year": 1928,
        "death_year": 2014,
        "profession": "Poet, Memoirist, and Civil Rights Activist",
        "achievements": [
            "Published seven autobiographies including 'I Know Why the Caged Bird Sings'",
            "Recited poem 'On the Pulse of Morning' at President Clinton's inauguration (1993)",
            "Received over 50 honorary degrees",
            "Won three Grammy Awards for spoken word albums",
            "Served as northern coordinator for Dr. King's Southern Christian Leadership Conference",
        ],
        "biography": "Maya Angelou was an American poet, singer, memoirist, and civil rights activist. She published seven autobiographies, three books of essays, several books of poetry, and is credited with a list of plays, movies, and television shows spanning over 50 years. She received dozens of awards and more than 50 honorary degrees.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/b4/Maya_Angelou_visit_YCP_Feb_4_2013.jpg",
        "category": "Arts & Literature",
    },
    {
        "id": 3,
        "name": "Katherine Johnson",
        "birth_year": 1918,
        "death_year": 2020,
        "profession": "NASA Mathematician & Space Scientist",
        "achievements": [
            "Calculated trajectory for Alan Shepard's space flight (1961)",
            "Verified orbital equations for John Glenn's mission (1962)",
            "Calculated Apollo 11 flight trajectory to the moon (1969)",
            "Worked on Space Shuttle and Earth Resources Satellite programs",
            "Received Presidential Medal of Freedom in 2015",
        ],
        "biography": "Katherine Johnson was an American mathematician whose calculations of orbital mechanics as a NASA employee were critical to the success of the first and subsequent U.S. crewed spaceflights. During her 35-year career at NASA and its predecessor, she earned a reputation for mastering complex manual calculations and helped pioneer the use of computers to perform the tasks.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/6/66/Katherine_Johnson_1983.jpg",
        "category": "Science & Technology",
    },
    {
        "id": 4,
        "name": "Malcolm X",
        "birth_year": 1925,
        "death_year": 1965,
        "profession": "Human Rights Activist & Minister",
        "achievements": [
            "Became prominent minister and national spokesperson for Nation of Islam",
            "Founded Muslim Mosque Inc. and Organization of Afro-American Unity",
            "Advocated for Black empowerment and Pan-Africanism",
            "Influential in civil rights movement through his advocacy for Black nationalism",
            "Autobiography published posthumously became a classic American memoir",
        ],
        "biography": "Malcolm X was an African American Muslim minister and human rights activist who was a prominent figure during the civil rights movement. A spokesman for the Nation of Islam until 1964, he was a vocal advocate for Black empowerment and the promotion of Islam within the Black community.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/57/Malcolm_X_NYWTS_2a.jpg",
        "category": "Civil Rights Leaders",
    },
    {
        "id": 5,
        "name": "Madame C.J. Walker",
        "birth_year": 1867,
        "death_year": 1919,
        "profession": "Entrepreneur & Philanthropist",
        "achievements": [
            "First female self-made millionaire in America",
            "Founded Madam C.J. Walker Manufacturing Company",
            "Developed specialized hair care products for Black women",
            "Employed thousands of Black women through direct sales",
            "Major philanthropist supporting education and civil rights",
        ],
        "biography": "Madame C.J. Walker was an African American entrepreneur, philanthropist, and political and social activist. She is recorded as the first female self-made millionaire in America in the Guinness Book of World Records. Walker made her fortune by developing and marketing a line of cosmetics and hair care products for Black women through her business, Madam C.J. Walker Manufacturing Company.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Madam_CJ_Walker_face_circa_1914.jpg",
        "category": "Business & Entrepreneurship",
    },
    {
        "id": 6,
        "name": "Thurgood Marshall",
        "birth_year": 1908,
        "death_year": 1993,
        "profession": "Supreme Court Justice & Civil Rights Lawyer",
        "achievements": [
            "First African American Supreme Court Justice (1967-1991)",
            "Successfully argued Brown v. Board of Education (1954)",
            "Founded NAACP Legal Defense and Educational Fund",
            "Argued 32 cases before Supreme Court, winning 29",
            "Champion of individual rights and liberal jurisprudence",
        ],
        "biography": "Thurgood Marshall was an American civil rights lawyer and jurist who served as an Associate Justice of the Supreme Court of the United States from 1967 until 1991. He was the Supreme Court's first African American justice. Before becoming a judge, he was a lawyer who was best known for his high success rate in arguing before the Supreme Court and for his victory in Brown v. Board of Education.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Thurgood_Marshall%2C_1976.jpg/800px-Thurgood_Marshall%2C_1976.jpg",
        "category": "Law & Justice",
    },
    {
        "id": 7,
        "name": "Rosa Parks",
        "birth_year": 1913,
        "death_year": 2005,
        "profession": "Civil Rights Activist",
        "achievements": [
            "Sparked Montgomery Bus Boycott by refusing to give up seat (1955)",
            "Became icon of resistance to racial segregation",
            "Worked with NAACP as secretary and youth leader",
            "Received Presidential Medal of Freedom (1996)",
            "Congressional Gold Medal (1999)",
        ],
        "biography": "Rosa Parks was an American activist in the civil rights movement best known for her pivotal role in the Montgomery bus boycott. The United States Congress has honored her as 'the first lady of civil rights' and 'the mother of the freedom movement'.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/19/Rosa_Parksbeingfingerprinted.jpg",
        "category": "Civil Rights Leaders",
    },
    {
        "id": 8,
        "name": "George Washington Carver",
        "birth_year": 1864,
        "death_year": 1943,
        "profession": "Agricultural Scientist & Inventor",
        "achievements": [
            "Developed over 300 products from peanuts",
            "Revolutionized Southern agriculture through crop rotation",
            "First Black student at Iowa State Agricultural College",
            "Head of Tuskegee Institute's agricultural department",
            "Invented numerous products from sweet potatoes and soybeans",
        ],
        "biography": "George Washington Carver was an American agricultural scientist and inventor who promoted alternative crops to cotton and methods to prevent soil depletion. He was the most prominent Black scientist of the early 20th century. While a professor at Tuskegee Institute, Carver developed techniques to improve soils depleted by repeated plantings of cotton.",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/8a/George_Washington_Carver_c1910.jpg",
        "category": "Science & Technology",
    },
]
