MARKETPLACE_PRODUCTS = [
    {
        "id": 1,
        "name": "I Know Why the Caged Bird Sings - Maya Angelou",
        "description": "The groundbreaking autobiography of Maya Angelou, chronicling her early life and journey to becoming one of America's most celebrated writers.",
        "price": 15.99,
        "category": "Books",
        "seller_id": 1,
        "image_urls": [
            "https://images-na.ssl-images-amazon.com/images/I/91pR9wGJ3zL.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/91pR9wGJ3zL._AC_UL600_SR600,400_.jpg",
        ],
        "tags": ["autobiography", "poetry", "civil rights", "literature", "black excellence"],
        "is_active": True,
        "stock_quantity": 50,
    },
    {
        "id": 2,
        "name": "Black History Month Educational Poster Set",
        "description": "Set of 12 high-quality educational posters featuring prominent Black historical figures. Perfect for classrooms, libraries, and home education.",
        "price": 29.99,
        "category": "Educational Materials",
        "seller_id": 1,
        "image_urls": [
            "https://m.media-amazon.com/images/I/71H4KkJhZVL._AC_SL1000_.jpg",
            "https://m.media-amazon.com/images/I/81QYXJ9+pVL._AC_SL1000_.jpg",
        ],
        "tags": ["education", "posters", "classroom", "black history", "teaching materials"],
        "is_active": True,
        "stock_quantity": 100,
    },
    {
        "id": 3,
        "name": "Madame C.J. Walker Hair Care Collection - Replica Set",
        "description": "Authentic replica collection of the original hair care products developed by Madame C.J. Walker, America's first self-made female millionaire.",
        "price": 89.99,
        "category": "Beauty & Personal Care",
        "seller_id": 2,
        "image_urls": [
            "https://m.media-amazon.com/images/I/81QYXJ9+pVL._AC_SL1000_.jpg",
            "https://m.media-amazon.com/images/I/91pR9wGJ3zL._AC_UL600_SR600,400_.jpg",
        ],
        "tags": ["hair care", "black owned", "madame walker", "historical", "beauty"],
        "is_active": True,
        "stock_quantity": 25,
    },
    {
        "id": 4,
        "name": "Hidden Figures - Young Readers' Edition",
        "description": "The inspiring story of four Black women who helped NASA launch men into space. Adapted for young readers with photos and historical context.",
        "price": 8.99,
        "category": "Books",
        "seller_id": 1,
        "image_urls": [
            "https://images-na.ssl-images-amazon.com/images/I/91pR9wGJ3zL.jpg",
            "https://images-na.ssl-images-amazon.com/images/I/81QYXJ9+pVL._AC_SL1000_.jpg",
        ],
        "tags": ["stem", "nasa", "katherine johnson", "young readers", "education"],
        "is_active": True,
        "stock_quantity": 75,
    },
    {
        "id": 5,
        "name": "Civil Rights Movement Documentary Collection",
        "description": "5-DVD collection featuring rare footage and interviews from the Civil Rights Movement, including the March on Washington and Montgomery Bus Boycott.",
        "price": 49.99,
        "category": "Digital Media",
        "seller_id": 3,
        "image_urls": [
            "https://m.media-amazon.com/images/I/71H4KkJhZVL._AC_SL1000_.jpg",
            "https://m.media-amazon.com/images/I/81QYXJ9+pVL._AC_SL1000_.jpg",
        ],
        "tags": ["documentary", "civil rights", "history", "dvd", "education"],
        "is_active": True,
        "stock_quantity": 30,
    },
    {
        "id": 6,
        "name": "Black Excellence Art Print - Katherine Johnson",
        "description": "High-quality art print celebrating Katherine Johnson's contributions to space exploration. Perfect for home, office, or classroom display.",
        "price": 24.99,
        "category": "Art & Collectibles",
        "seller_id": 4,
        "image_urls": [
            "https://m.media-amazon.com/images/I/81QYXJ9+pVL._AC_SL1000_.jpg",
            "https://m.media-amazon.com/images/I/91pR9wGJ3zL._AC_UL600_SR600,400_.jpg",
        ],
        "tags": ["art", "katherine johnson", "nasa", "black excellence", "print"],
        "is_active": True,
        "stock_quantity": 40,
    },
    {
        "id": 7,
        "name": "George Washington Carver - Agricultural Science Kit",
        "description": "Educational science kit inspired by George Washington Carver's agricultural innovations. Includes materials for 10 hands-on experiments.",
        "price": 34.99,
        "category": "Educational Materials",
        "seller_id": 5,
        "image_urls": [
            "https://m.media-amazon.com/images/I/71H4KkJhZVL._AC_SL1000_.jpg",
            "https://m.media-amazon.com/images/I/81QYXJ9+pVL._AC_SL1000_.jpg",
        ],
        "tags": ["science", "agriculture", "george washington carver", "education", "experiments"],
        "is_active": True,
        "stock_quantity": 60,
    },
    {
        "id": 8,
        "name": "Black Wall Street - Tulsa Race Massacre Memorial Book",
        "description": "Comprehensive history of Black Wall Street and the 1921 Tulsa Race Massacre, including survivor testimonies and rare photographs.",
        "price": 22.99,
        "category": "Books",
        "seller_id": 6,
        "image_urls": [
            "https://images-na.ssl-images-amazon.com/images/I/91pR9wGJ3zL.jpg",
            "https://m.media-amazon.com/images/I/81QYXJ9+pVL._AC_SL1000_.jpg",
        ],
        "tags": ["tulsa", "black wall street", "history", "memorial", "1921"],
        "is_active": True,
        "stock_quantity": 45,
    },
    {
        "id": 9,
        "name": "African American Inventors Flash Cards",
        "description": "Set of 50 educational flash cards featuring African American inventors and their groundbreaking innovations. Perfect for students and educators.",
        "price": 18.99,
        "category": "Educational Materials",
        "seller_id": 1,
        "image_urls": [
            "https://m.media-amazon.com/images/I/71H4KkJhZVL._AC_SL1000_.jpg",
            "https://m.media-amazon.com/images/I/81QYXJ9+pVL._AC_SL1000_.jpg",
        ],
        "tags": ["flash cards", "inventors", "education", "students", "learning"],
        "is_active": True,
        "stock_quantity": 80,
    },
    {
        "id": 10,
        "name": "Harlem Renaissance Coffee Table Book",
        "description": "Beautifully illustrated coffee table book celebrating the artists, writers, and musicians of the Harlem Renaissance era (1920s-1930s).",
        "price": 45.99,
        "category": "Books",
        "seller_id": 7,
        "image_urls": [
            "https://images-na.ssl-images-amazon.com/images/I/91pR9wGJ3zL.jpg",
            "https://m.media-amazon.com/images/I/81QYXJ9+pVL._AC_SL1000_.jpg",
        ],
        "tags": ["harlem renaissance", "art", "coffee table book", "culture", "illustrated"],
        "is_active": True,
        "stock_quantity": 35,
    },
]
